"""empty message

Revision ID: 496d5a6566b2
Revises: 4844eeb7c424
Create Date: 2024-06-06 00:51:21.258877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '496d5a6566b2'
down_revision = '4844eeb7c424'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('terrain', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('residing_planet', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'planet', ['residing_planet'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('residing_planet')

    op.drop_table('planet')
    # ### end Alembic commands ###
