"""empty message

Revision ID: 988999d3ef23
Revises: 496d5a6566b2
Create Date: 2024-06-06 00:53:57.522492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '988999d3ef23'
down_revision = '496d5a6566b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=250), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
