"""empty message

Revision ID: 99e733493fe3
Revises: 9721ad3b687b
Create Date: 2024-06-08 01:14:17.320827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99e733493fe3'
down_revision = '9721ad3b687b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id_favorites', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id_favorites'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorite_planets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id_favorites', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id_favorites'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('favorite__people')
    op.drop_table('favorite__planets')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite__planets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id_favorites', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id_favorites'], ['users.id'], name='favorite__planets_user_id_favorites_fkey'),
    sa.PrimaryKeyConstraint('id', name='favorite__planets_pkey')
    )
    op.create_table('favorite__people',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id_favorites', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id_favorites'], ['users.id'], name='favorite__people_user_id_favorites_fkey'),
    sa.PrimaryKeyConstraint('id', name='favorite__people_pkey')
    )
    op.drop_table('favorite_planets')
    op.drop_table('favorite_people')
    # ### end Alembic commands ###
